### ISSUE TITLE
EFI 会造成崩溃，自动重启

### ISSUE THREAD

**Issue by flyflas** [daliansky/minisforum-UM560XT-Hackintosh#1]
## 硬件
* 16GB 2400Mhz 内存（已经设置为4GB显存）
* 致态TI5000 1T硬盘
* Intel 7265NGW 无线网卡

## EFI 地址
[有问题的EFI](https://github.com/flyflas/UM560XT-EFI)

## 问题描述
启动`Ventura`,  使用 -v 命令之后，跑码跑到ACMTRP这个阶段之后，便会自动重启。

![image](https://github.com/daliansky/minisforum-UM560XT-Hackintosh/assets/124574439/b6e7f0e6-aebd-435d-9f50-1a38f9e2a575)
![image](https://github.com/daliansky/minisforum-UM560XT-Hackintosh/assets/124574439/cba3d118-57c6-43f5-b2ca-f9bf129b59d3)

## 猜测原因
应该是NootedRed核显驱动的问题，在禁用该驱动之后，可以顺利的完成安装，进入系统。但是在启用NootedRed之后，跑码到一半，便会直接重启

## 其他
是不是UM560XT不同批次的硬件不同？我看老白的视频，前面的C口可以输出超过4K@60HZ的画面。但是我外接4K@120Hz的便携屏的时候，最高只有4K@60HZ。

**Comment by ghost** [comment]
问题+1 类似的问题，去掉NootedRed可以进入安装页面，安装完成后就一直重启，想去清除NVRAM无法再次进入oc选择。

**Comment by flyflas** [comment]
> 问题+1 类似的问题，去掉NootedRed可以进入安装页面，安装完成后就一直重启，想去清除NVRAM无法再次进入oc选择。

你内存的频率是多少的？我怀疑是内存频率的问题

**Comment by ghost** [comment]
> 

我是2666的之前老机子留下来的，毕竟现在才尝鲜版，肯定是有很多隐藏的问题。

**Comment by ghost** [comment]
> > 问题+1 类似的问题，去掉NootedRed可以进入安装页面，安装完成后就一直重启，想去清除NVRAM无法再次进入oc选择。
> 
> 你内存的频率是多少的？我怀疑是内存频率的问题

我这边昨天试了下，big sur可以装，cpu和igpu的睿频一塌糊涂，核显基本都是满载运行，什么都不动整机功耗基本在30w上下，用开源的amd电源管理可以把cpu的频率拉低，可是核显还是满载。整机功耗在20w上下，兄弟我感觉你也别整了，很糟心。

**Comment by kilroylau** [comment]
Ventura 先在其它電腦安裝好硬盤，EFI，然後才插到UM560主機上，開機，可以正常使用。

https://github.com/Xmingbai/Minisforum-UM560-UM580-APU-Hackintosh

**Comment by ghost** [comment]
> Ventura 先在其它電腦安裝好硬盤，EFI，然後才插到UM560主機上，開機，可以正常使用。
> 
> https://github.com/Xmingbai/Minisforum-UM560-UM580-APU-Hackintosh

你这个就有玄学成分在里面了，我个人感觉应该是产品的bios差异，博主用的是厂家特供的机型，用于博主评测用的，所以他们都说是海外版，和内地版本可能有一定的区别，在一些bios设置上海外版的没有可是内地版的有。

**Comment by kilroylau** [comment]
國內淘寶版

**Comment by ghost** [comment]
> 國內淘寶版

我这边也装好了，版本不对，不知道为什么需要13.4才能，我一直装的13.1
